name: NodeJS with Webpack

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8.7.5
        run_install: false

    - name: Install dependence
      run: pnpm i

    - name: Generate Electron
      run: pnpm run "/^build:.*/"
      
    - name: Setup electron-forge 
      run:  pnpm electron-forge import
  
    - name: Publish
      run: pnpm pub

    - uses: softprops/action-gh-release@v1
      with:
       files: out/*
